 ; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs


; Library dependencies used by the project. These may be adjusted to specific
; versions if needed. They cover the SH1106 driver, async web server, async
; TCP, async ping, LittleFS and ArduinoJson for JSON handling.
lib_deps =
	me-no-dev/ESPAsyncWebServer
	me-no-dev/AsyncTCP
	bblanchon/ArduinoJson@^6.20.0
	olikraus/U8g2
	marian-craciunescu/ESP32Ping

build_flags =
	-D MAX_HOSTS=20
	-D DEFAULT_PING_INTERVAL_SEC=3
	-D DEFAULT_PING_TIMEOUT_MS=1000
